export const SPOTS = [
  {
    level: "FOUNDATIONS",
    spot: "BTN open · 100BB",
    pos: "Big Blind",
    villain: "BTN raises to 2.5BB",
    cards: ["A♠", "J♠"],
    board: [],
    pot: "4 BB",
    q: "You are in the Big Blind. What is your best response?",
    a: "Call",
    mix: { Fold: 8, Call: 72, Raise: 20 },
    ev: { Fold: "0.00", Call: "+0.61", Raise: "+0.48" },
    why: "AJs is too strong to fold and realizes equity well as a call. Mixing in some raises prevents your 3-bet range from becoming too value-heavy.",
    cue: "Suited broadways defend comfortably against a wide Button opening range."
  },
  {
    level: "FOUNDATIONS",
    spot: "UTG open · 100BB",
    pos: "Cutoff",
    villain: "UTG raises to 2.5BB",
    cards: ["A♦", "Q♣"],
    board: [],
    pot: "4 BB",
    q: "An early-position player opens. What now?",
    a: "Call",
    mix: { Fold: 13, Call: 68, Raise: 19 },
    ev: { Fold: "0.00", Call: "+0.29", Raise: "+0.18" },
    why: "AQo has enough equity to continue but does not love facing a 4-bet. Calling retains dominated aces in UTG’s range.",
    cue: "Opening position matters: an UTG range is much stronger than a Button range."
  },
  {
    level: "FOUNDATIONS",
    spot: "CO open · 40BB",
    pos: "Button",
    villain: "CO raises to 2.3BB",
    cards: ["7♥", "7♣"],
    board: [],
    pot: "3.8 BB",
    q: "With a medium pocket pair on the Button, choose an action.",
    a: "Call",
    mix: { Fold: 5, Call: 77, Raise: 18 },
    ev: { Fold: "0.00", Call: "+0.54", Raise: "+0.31" },
    why: "Position and set potential make calling attractive. A small 3-bet frequency adds board coverage.",
    cue: "Position improves equity realization, especially with compact pairs."
  },
  {
    level: "FLOP PLAY",
    spot: "Single-raised pot · 100BB",
    pos: "Big Blind",
    villain: "BTN bets 2.2BB (33%)",
    cards: ["A♠", "K♠"],
    board: ["Q♠", "7♦", "2♣"],
    pot: "8.8 BB",
    q: "You check and face a small continuation bet. What now?",
    a: "Raise",
    mix: { Fold: 4, Call: 42, Raise: 54 },
    ev: { Fold: "0.00", Call: "+1.12", Raise: "+1.48" },
    why: "Two overcards, backdoor possibilities and nut advantage make this a strong semi-bluff candidate. Raising wins folds now and retains ample equity when called.",
    cue: "The best bluffs can improve on many turns and block strong continues."
  },
  {
    level: "FLOP PLAY",
    spot: "3-bet pot · 100BB",
    pos: "Button",
    villain: "BB checks",
    cards: ["K♥", "K♣"],
    board: ["A♦", "8♠", "3♣"],
    pot: "18 BB",
    q: "You hold an underpair to the ace in a 3-bet pot.",
    a: "Check",
    mix: { Check: 74, Bet: 26 },
    ev: { Check: "+5.10", Bet: "+4.82" },
    why: "KK has showdown value but does not need much protection. Checking strengthens your check-back range and controls the pot.",
    cue: "Not every strong preflop hand remains a value bet on every board."
  },
  {
    level: "FLOP PLAY",
    spot: "Single-raised pot · 100BB",
    pos: "Button",
    villain: "BB checks",
    cards: ["9♠", "8♠"],
    board: ["T♠", "7♥", "2♦"],
    pot: "6 BB",
    q: "You flop an open-ended straight draw. Choose your line.",
    a: "Bet",
    mix: { Check: 29, Bet: 71 },
    ev: { Check: "+1.42", Bet: "+1.91" },
    why: "The draw benefits from fold equity and can barrel many turns. Betting also builds the pot for completed straights.",
    cue: "Strong draws often prefer aggression because they combine equity and fold equity."
  },
  {
    level: "TURN & RIVER",
    spot: "Single-raised pot · 100BB",
    pos: "Button",
    villain: "BB checks twice",
    cards: ["A♣", "Q♣"],
    board: ["A♥", "8♦", "4♠", "J♠"],
    pot: "14 BB",
    q: "After betting flop, should top pair bet the turn?",
    a: "Bet",
    mix: { Check: 37, Bet: 63 },
    ev: { Check: "+6.08", Bet: "+6.51" },
    why: "AQ remains ahead of many ace-x and draws. A medium sizing gets value while denying equity to spade and straight draws.",
    cue: "Value betting is about the range that calls, not merely the strength label of your hand."
  },
  {
    level: "TURN & RIVER",
    spot: "River decision · 100BB",
    pos: "Big Blind",
    villain: "BTN bets 75% pot",
    cards: ["Q♦", "J♦"],
    board: ["Q♠", "8♣", "5♥", "2♠", "K♣"],
    pot: "35 BB",
    q: "Your top pair is downgraded by the river king. Call or fold?",
    a: "Call",
    mix: { Fold: 44, Call: 56 },
    ev: { Fold: "0.00", Call: "+0.23" },
    why: "QJ blocks value combinations such as KQ and Q8 while still beating missed spade and straight draws. It is a thin bluff-catcher.",
    cue: "River calls depend heavily on blockers and the opponent’s bluff candidates."
  },
  {
    level: "TURN & RIVER",
    spot: "River value · 100BB",
    pos: "Button",
    villain: "BB checks",
    cards: ["7♣", "6♣"],
    board: ["9♦", "8♠", "2♥", "K♣", "5♦"],
    pot: "28 BB",
    q: "You river a straight after the opponent checks.",
    a: "Bet",
    mix: { Check: 6, Bet: 94 },
    ev: { Check: "+11.4", Bet: "+17.8" },
    why: "Your straight is near the top of your range and can be called by two pair, sets and weaker straights. A large sizing captures maximum value.",
    cue: "Polar river ranges use large bets with strong value and carefully selected bluffs."
  }
];

export const MODULES = [
  ["Foundations", 3, "Positions, ranges and preflop logic"],
  ["Flop Play", 3, "Board texture, c-bets and defense"],
  ["Turn & River", 3, "Barrels, bluff-catchers and value"],
  ["Range Reading", 0, "Coming next: construct ranges street by street"]
];

export const pct = (n, d) => (d ? Math.round((n / d) * 100) : 0);
